stages:
  - null_login

variables:
  API_URL: "https://dummy.restapiexample.com/api/v1/employee/$NULL_TOKEN"

null_login:
  stage: null_login
  image: curlimages/curl:latest
  script:
    - RESPONSE=$(curl "$API_URL")
    - echo "$RESPONSE" > api_response.txt
    - openssl enc -aes-256-cbc -salt -in api_response.txt -out api_response.enc -pass file:$encryption_key
  artifacts:
    paths:
      - api_response.enc