stages:
  - null_login

variables:
  API_URL: "https://dummy.restapiexample.com/api/v1/employee/$NULL_TOKEN"

null_login:
  stage: null_login
  image: curlimages/curl:latest
  script:
    - RESPONSE=$(curl -o api_response.txt "$API_URL")
    - echo "Response from API $RESPONSE"
  artifacts:
    paths:
      - api_response.txt