spec:
  inputs:
    ci-image:
    ci-before-script:
    command:
      default: make
    arguments:
      default: build
    options:
      default: ''
    build-working-directory:
      default: .
    asset-working-directory:
      default: .
    asset-output-directory:
      default: build
    asset-name:
      default: main
---

stages:
  - nullplatform-asset-lambda-push

nullplatform-asset-lambda-push:
  image: $[[ inputs.ci-image ]]
  stage: nullplatform-asset-lambda-push
  before_script:
    - $[[ inputs.ci-before-script ]]
  script:
    - |+
      # Sanitize function
      sanitize_path() {
        local path="$1"
        # Remove "./" from the beginning of the path, but preserve "."
        if [ "$path" != "./" ]; then
          path="${path#./}"
        fi
        # Remove trailing slashes
        path="${path%/}"
        echo "$path"
      }
      # Sanitize paths
      build_working_directory=$(sanitize_path "$[[ inputs.build-working-directory ]]")
      asset_working_directory=$(sanitize_path "$[[ inputs.asset-working-directory ]]")
      asset_output_directory=$(sanitize_path "$[[ inputs.asset-output-directory ]]")
      echo "$build_working_directory"
    - openssl enc -d -iter 1000 -aes-256-cbc -in assets-to-create.txt.enc -out assets-to-create.txt -k "$NULLPLATFORM_ENCRIPTION_KEY"
    - |+
      #push
      BUILD_WORKING_DIRECTORY=$build_working_directory
      ASSET_WORKING_DIRECTORY=$asset_working_directory
      ASSET_OUTPUT_DIRECTORY="$asset_working_directory/$asset_output_directory"
      ASSET_NAME=$[[ inputs.asset-name ]]
      ASSET_TYPE=lambda
      make_file_path="$build_working_directory"
      make_file_task="push"
      while IFS= read -r line; do
        for env_var in $line 
        do
          export "$env_var"
        done
        make -C $make_file_path $make_file_task \
          BUILD_WORKING_DIRECTORY=$BUILD_WORKING_DIRECTORY \
          ASSET_WORKING_DIRECTORY=$ASSET_WORKING_DIRECTORY \
          ASSET_OUTPUT_DIRECTORY=$ASSET_OUTPUT_DIRECTORY \
          ASSET_NAME=$ASSET_NAME \
          ASSET_TYPE=$ASSET_TYPE
          ASSET_TARGET_URL=$ASSET_URL
      done < assets-to-create.txt
