image: alpine:latest
stages:
  - nullplatform-asset-docker-image-build-and-push

nullplatform-asset-docker-image-build-and-push:
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  stage: nullplatform-asset-docker-image-build-and-push
  before_script:
    - apk add --no-cache openssl
  script:
    -  mkdir -p /kaniko/.docker
    -  echo "{\"credsStore\":\"ecr-login\"}" > /kaniko/.docker/config.json
    - |+ 
      while IFS= read -r line; do
        for env_var in $line 
        do
          export "$env_var"
        done
        /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $ASSET_URL
      done < assets-to-create.txt
