stages:
  - nullplatform-asset-docker-image-build-and-push

nullplatform-asset-docker-image-build-and-push:
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  stage: nullplatform-asset-docker-image-build-and-push
    before_script:
      - apk update
      - apk add --no-cache openssl
  script:
    - openssl enc -d -iter 1000 -aes-256-cbc -in assets-to-create.txt.enc -out assets-to-create.txt -k "$NULLPLATFORM_ENCRIPTION_KEY"
    - |+ 
      while IFS= read -r line; do
        for env_var in $line 
        do
          echo $env_var
          export "$env_var"
        done
        echo $AWS_DEFAULT_REGION
        echo $AWS_SECRET_ACCESS_KEY
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
        /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $ASSET_URL
        docker push $ASSET_URL
      done < assets-to-create.txt
