stages:
  - nullplatform-asset-docker-image-build-and-push

nullplatform-asset-docker-image-build-and-push:
  image: docker:stable
  stage: nullplatform-asset-docker-image-build-and-push
  services:
    - docker:dind
  before_script:
    - apk add --no-cache python3 py3-pip
    - pip3 install --no-cache-dir awscli
  script:
    - cat assets-to-create.txt
    - |+ 
      while IFS= read -r line; do
        echo $line
        read -ra env_vars <<< "$line"
      done < assets-to-create.txt
