stages:
  - nullplatform-login

variables:
  NULLPLATFORM_LOGIN_URL: "https://github-actions.nullplatform.io/login"

nullplatform-login:
  stage: nullplatform-login
  image: ubuntu:latest
  before_script:
    - apt-get update
    - apt-get install -y openssl curl
  script:
    - curl -X POST \
        -H "Content-Type: application/json" \
        -d "{\"token\": \"$NULLPLATFORM_APIKEY\"}" \
        $NULLPLATFORM_LOGIN_URL > nullplatform_login.response.json
    - openssl enc -iter 1000 -aes-256-cbc -salt -in nullplatform_login.response.json -out nullplatform_login.response.json.enc -pass file:$encription_key
  artifacts:
    paths:
      - nullplatform_login.response.json.enc