stages:
  - nullplatform-application-metadata

variables:
  NULLPLATFORM_APPLICATION_METADATA_URL: "https://github-actions.nullplatform.io/application"
  NULLPLATFORM_APPLICATION_METADATA_PARAMS: "repository_url=$CI_PROJECT_URL"
  NULLPLATFORM_APPLICATION_METADATA_HEADERS: "Content-Type: application/json"

nullplatform-application-metadata:
  stage: nullplatform-application-metadata
  image: ubuntu:latest
  before_script:
    - apt-get update
    - apt-get install -y openssl curl jq
    - openssl enc -d -iter 1000 -aes-256-cbc -in nullplatform_login.response.json.enc -out nullplatform_login.response.json -pass file:$encription_key
    - ACCESS_TOKEN=$(cat nullplatform_login.response.json | jq -r '.access_token')
  script:
    - COMMAND="curl -H \"Authorization:$ACCESS_TOKEN\" -H \"$NULLPLATFORM_APPLICATION_METADATA_HEADERS\" -d \"$NULLPLATFORM_APPLICATION_METADATA_BODY\" \"$NULLPLATFORM_APPLICATION_METADATA_URL?$NULLPLATFORM_APPLICATION_METADATA_PARAMS\""
    - echo $COMMAND    
    - NULLPLATFORM_APPLICATION_METADATA_RESPONSE=$(curl -H "Authorization:$ACCESS_TOKEN" -H "$NULLPLATFORM_APPLICATION_METADATA_HEADERS" -d "$NULLPLATFORM_APPLICATION_METADATA_BODY" "$NULLPLATFORM_APPLICATION_METADATA_URL?$NULLPLATFORM_APPLICATION_METADATA_PARAMS")
    - echo "$NULLPLATFORM_APPLICATION_METADATA_RESPONSE" 
    - echo "$NULLPLATFORM_APPLICATION_METADATA_RESPONSE" > nullplatform_application_metadata.response.json
  artifacts:
    paths:
      - nullplatform_application_metadata.response.json