stages:
  - nullplatform-asset-docker-image-build-and-push

nullplatform-asset-docker-image-build-and-push:
  image: docker:stable
  stage: nullplatform-asset-docker-image-build-and-push
  services:
    - docker:dind
  before_script:
    - apk add --no-cache python3 py3-pip
    - pip3 install --no-cache-dir awscli
  script:
    - cat assets-to-create.txt
    - |+ 
      while IFS= read -r line; do
        for env_var in $line 
        do
          export "$env_var"
        done
        echo $AWS_DEFAULT_REGION
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
        docker build -t $ASSET_URL .
        docker push $ASSET_URL
      done < assets-to-create.txt
