stages:
  - nullplatform-asset-docker-image-create

variables:
  NULLPLATFORM_URL: "https://ci.nullplatform.com" #build/:id/asset
  NULLPLATFORM_ASSET_HEADERS: "Content-Type: application/json"

nullplatform-asset-docker-image-create:
  stage: nullplatform-asset-docker-image-create
  image: ubuntu:latest
  before_script:
    - apt-get update
    - apt-get install -y openssl curl jq unzip
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - curl -fsSL https://get.docker.com -o get-docker.sh
    - sh ./get-docker.sh
    - openssl enc -d -iter 1000 -aes-256-cbc -in nullplatform_login.response.json.enc -out nullplatform_login.response.json -pass file:$encription_key
    - ACCESS_TOKEN=$(cat nullplatform_login.response.json | jq -r '.access_token')
  script:
    - |+
      while IFS= read -r line; do
        BUILD_ID=$(echo "$line" | jq -r '.id')
        APPLICATION_ID=$(echo "$line" | jq -r '.application_id')
        NULLPLATFORM_ASSET_CREATE_BODY="{\"type\":\"docker-image\",\"metadata\":{}}"
        NULLPLATFORM_ASSET_CREATE_RESPONSE=$(curl -X POST -H "$NULLPLATFORM_ASSET_HEADERS" -H "Authorization:Bearer $ACCESS_TOKEN" -d "$NULLPLATFORM_ASSET_CREATE_BODY" $NULLPLATFORM_URL/build/$BUILD_ID/asset)
        for ASSET_URL in $(echo "$NULLPLATFORM_ASSET_CREATE_RESPONSE" | jq -r '.targets[].url'); do
          echo $ASSET_URL
          NULLPLATFORM_APPLICATION_PARAMETERS=$(curl -H "Authorization:Bearer $ACCESS_TOKEN" $NULLPLATFORM_URL/application/$APPLICATION_ID/parameter)
          echo $NULLPLATFORM_APPLICATION_PARAMETERS
          for parameter in $(echo "$NULLPLATFORM_APPLICATION_PARAMETERS" | jq -c '.[]'); do
            name=$(echo "$parameter" | jq -r '.name')
            value=$(echo "$parameter" | jq -r '.value')
            if [ "$value" != "null" ]; then
              eval "$name=\"$value\""
            fi
          done
          export AWS_ACCESS_KEY_ID="$BUILD_AWS_ACCESS_KEY"
          export AWS_SECRET_ACCESS_KEY="$BUILD_AWS_SECRET_ACCESS_KEY"
          export AWS_DEFAULT_REGION="$BUILD_AWS_REGION"
          ECR_REGISTRY=$(echo "$ASSET_URL" | cut -d '/' -f 1)
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
          docker build -t $ASSET_URL .
          #docker push $ASSET_URL
        done
        echo $NULLPLATFORM_ASSET_CREATE_RESPONSE
        printf "%s\n" $NULLPLATFORM_ASSET_CREATE_RESPONSE >> nullplatform-asset-create.json
      done < nullplatform-build-create.json 
  artifacts:
    paths:
      - nullplatform-asset-create.json
    expire_in: 30 min

